// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"tovenaar/db"

	"github.com/99designs/gqlgen/graphql"
)

type AnswerInput struct {
	QuestionID string         `json:"questionId"`
	File       graphql.Upload `json:"file"`
}

type Authentication struct {
	Token string        `json:"token"`
	User  *db.UserModel `json:"user"`
}

type AuthenticationInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CollectionInput struct {
	Email   string        `json:"email"`
	Answers []AnswerInput `json:"answers"`
}

type IDInput struct {
	ID string `json:"id"`
}

type QuestionInput struct {
	ID    *string `json:"id"`
	Text  string  `json:"text"`
	Order int     `json:"order"`
}
